name: Build Mod

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true  # fetch Foundation

    - name: Setup Build Dependencies
      run: |
        $version = $(Get-Content .\modinfo.json | jq -r .dependencies.game)
        $filename = "vs_server_${version}.tar.gz"
        $folder = if ($version -like "*-rc*") { "unstable" } else { "stable" }
        $uri = "https://cdn.vintagestory.at/gamefiles/${folder}/${filename}"
        Invoke-WebRequest -Uri $uri -Out $filename
        $vsdir = $(mkdir VintageStory)
        cd VintageStory
        tar -zxvf "..\$filename" Lib/ Mods/ VintagestoryAPI.dll
        Add-Content -Path $Env:GITHUB_ENV -Value "VINTAGE_STORY=${vsdir.FullPath}"
      shell: pwsh

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore Mod
      run: msbuild /t:Restore /p:Configuration=Release

    - name: Build Mod
      run: msbuild /t:Build /p:Configuration=Release
      env:
        VINTAGE_STORY: ${{ env.VINTAGE_STORY }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Mod
        path: .

    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
